### ISSUE TITLE
relative path resolving for command line

### ISSUE THREAD

**Issue by isysd** [gangverk/flask-swagger#17]
Transferred from: https://github.com/deginner/flask-swagger/issues/3

The command line interface is currently very picky about parsing the app argument. For example, even if you add an `__init__.py` file to ./examples, or add examples to setup.py then install it, the example is not discoverable by flaskswagger.

```
flaskswagger flask_swagger.examples.example:app
~/.virtualenv/swagxample/local/lib/python2.7/site-packages/pkg_resources/__init__.py:1256: UserWarning: ~/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "~/.virtualenv/swagxample/bin/flaskswagger", line 9, in <module>
    load_entry_point('flask-swagger==0.2.11', 'console_scripts', 'flaskswagger')()
  File "~/.virtualenv/swagxample/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "~/.virtualenv/swagxample/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "~/.virtualenv/swagxample/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "~/.virtualenv/swagxample/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/build_swagger_spec.py", line 28, in <module>
  File "build/bdist.linux-x86_64/egg/build_swagger_spec.py", line 15, in run
  File "~/.virtualenv/swagxample/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "~/.virtualenv/swagxample/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named examples.example
```

One or both of these use cases should be supported.

**Comment by atlithorn** [comment]
Hey Ira, once this is resolved I'll push 0.2.11 to pypi
